### ISSUE TITLE
Cocoa Pods

### ISSUE THREAD

**Issue by dgabeau** [learn-co-curriculum/ios-environment-setup-summary#3]
I did not have cocoa already installed on my computer after installing Learn. There were no directions for what to do about that. I ran 'gem install cocoapods', but a complete beginner might be stuck.

**Comment by AnnJohn** [comment]
Iceboxing the issue. Has been raised multiple times and should be revisited soon.

**Comment by markedwardmurray** [comment]
I think the Learn App's installation process got patched a while ago.
