### ISSUE TITLE
Cocoapods 

### ISSUE THREAD

**Issue by sarahparmenter** [learn-co-curriculum/ios-environment-setup-summary#4]
It would be really handy here to know what to do if you indeed get - 
-bash: pod: command not found

I had to do 
sudo gem update --system 
and then 
sudo gem install cocoapods

After Googling for the answer.

**Comment by AnnJohn** [comment]
Iceboxing the issue. Has been raised multiple times and should be revisited soon.

**Comment by markedwardmurray** [comment]
I think the Learn app got fixed a while back.
