### ISSUE TITLE
how to setup the environment on windows 10?

### ISSUE THREAD

**Issue by hkxnyc** [learn-co-curriculum/ios-environment-setup-summary#8]
I am stuck on the first lab since I could not setup the environment on my windows.
Is there a procedure that I can follow to setup Git & GitHub on my windows?

Thank you!

**Comment by markedwardmurray** [comment]
Sorry Hannah, but due to Xcode, the iOS course can only be completed on a Mac running OS X. If you're interested in the web course, you can use a virtual environment through Nitrous from your Windows machine.
